name: security

on: push

jobs:
  check-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag adioss/dockerhub-sensitive-data-collector:latest
      - name: Scan image with Anchore
        uses: anchore/scan-action@v2
        with:
          image: "adioss/dockerhub-sensitive-data-collector:latest"
          fail-build: true
          debug: false
          severity-cutoff: critical
          acs-report-enable: true
      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
      - name: Find Secrets
        uses: max/secret-scan@master